version: '3.1'
services:
  app:
    container_name: backendtask
    image: backendtask
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - rabbitmq
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.5.3-management
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backendtask